INSERT INTO products (productName, productDesc, productType, productPrice, image_url) VALUES
-- Mice Products
('Luxuper M-A - Compact Mouse',
'Ambidextrous, compact design emphasizing comfort and simplicity. Engineered with an aluminum scroll wheel, dedicated DPI button for up to 3,000 DPI & an additional programmable button for multi-use. 125-1,000 Hz polling rate.',
'Mice',
17.99,
'images/'),

('Luxuper M-AW - Wireless Compact Mouse',
'Wireless version of the Luxuper M-A. All features included, with up to 20 hours battery life. Bluetooth-compatible, also usable with included Type-C wire and/or USB-A 2.4GHz dongle.',
'Mice',
29.99,
'images/'),

('Luxuper M-C - Lightweight Ergonomic Mouse',
'Lightweight compact mouse designed for efficiency, with silent click switches. Engineered with an aluminum scroll wheel, dedicated DPI button for up to 4,000 DPI & an additional programmable button for multi-use. True 1,000 Hz polling rate.',
'Mice',
35.99,
'images/'
),
('Luxuper M-CW - Wireless Lightweight Ergonomic Mouse',
'Wireless version of the Luxuper M-C. All features included, with up to 40 hours battery life. Bluetooth-compatible, also usable with included Type-C wire and/or USB-A dongle. Charging dock included.',
'Mice',
45.99,
'images/'),

('Luxuper M-Cx Pro - Ergonomic Mouse',
'Designed with quality in mind. An upgrade from the compact version, with an advanced vertical design, full aluminum frame. Features a dedicated DPI button for up to 12,000 DPI, 6 programmable buttons, and a customizable RGB indicator. 4000-8000Hz polling rate.',
'Mice',
69.99,
'images/'),

('Luxuper M-CWx Pro - Wireless Ergonomic Mouse',
'Compared to the Luxuper M-Cx Pro model, the M-CWx Pro includes all features presented with an additional charging dock, customizable side-scroll wheel, and underglow LED lighting.',
'Mice',
110.99,
'images/'),



-- Keyboard Products
('Luxuper Type E - Ergonomic Full Size Keyboard',
'The Luxuper',
'Keyboard',
75.99,
'images/'),
('Luxuper Type E-TKL - (TKL) Ergonomic Full Size Keyboard',
'',
'Keyboard',
59.99),
('Luxuper Type EW - Wireless Ergonomic Full Size Keyboard',
'',
'Keyboard',
95.99,
'images/'),
('Luxuper Type EW-TKL - (TKL) Wireless Ergonomic Full Size Keyboard',
'',
'Keyboard',
65.99,
'images/'),
('Luxuper Type Pro E - Ergonomic Aluminum-Alloy Full Size Keyboard',
'',
'Keyboard',
129.99,
'images/')
('Luxuper Type Pro E-TKL - Ergonomic Aluminum-Alloy TKL Keyboard',
'',
'Keyboard',
99.99,
'images/')
('Luxuper Type Pro EW - Wireless Ergonomic Aluminum-Alloy Full Size Keyboard',
'',
'Keyboard',
199.99,
'images/')
('Luxuper Type Pro EW-TKL - Ergonomic Wireless Ergonomic Aluminum-Alloy TKL Keyboard',
'',
'Keyboard',
145.99)


-- Desk Mat Products
('Luxuper Desk Mat XL',
'Genuine full-grain leather delivers functionality with anti-slip bases and refined finish. Protect your desk from scratches, spills, and typical wear and tear. Raised padding along the edge for wrist comfort. Size XL, 400x800mm.',
'Mousepad',
55.99,
'images/'),
('Luxuper Desk Mat L',
'Genuine full-grain leather delivers functionality with anti-slip bases and refined finish. Protect your desk from scratches, spills, and typical wear and tear. Raised padding along the edge for wrist comfort. Size L, 400x450mm.',
'Mousepad',
45.99,
'images/',
),
('Luxuper Desk Mat M',
'Genuine full-grain leather delivers functionality with anti-slip bases and a refined finish. Protect your desk from scratches, spills, and typical wear and tear. Raised padding along the edge for wrist comfort. Size M, 300x350mm.',
'Mousepad',
35.99,
'images/'
),
('Luxuper Desk Mat S',
'Genuine full-grain leather delivers functionality with anti-slip bases and refined finish. Protect your desk from scratches, spills, and typical wear and tear. Raised padding along the edge for wrist comfort. Size S, 200x250mm.',
'Mousepad',
25.99,
'images/'),
('Luxuper Desk Bundle XL',
'Size XL - Includes our top of the notch full-grain desk mat with added wrist support. Bundled with the Luxuper Type-E Keyboard & M-A mouse.',
'Bundles',
149.99,
'images/'),
('Luxuper Desk Bundle L',
'Size L - Includes our top of the notch full-grain desk mat with added wrist support. Bundled with the Luxuper Type-E Keyboard & M-A mouse.',
'Bundles',
140.99,
'images/'),
('Luxuper Desk Bundle M',
'Size M - Includes our top of the notch full-grain desk mat with added wrist support. Bundled with the Luxuper Type-E Keyboard & M-A mouse.',
'Bundles',
130.99,
'images/'
),
('Luxuper Desk Bundle S',
'Size S - Includes our top of the notch full-grain desk mat with added wrist support. Bundled with the Luxuper Type-E Keyboard & M-A mouse.',
120.99,
'images/'
),

-- Audio Products
('Luxuper Firebrand',
'High quality condenser microphone with a cardioid polar pattern, perfect for streaming or podcasting.',
'Microphone',
449.99,
'images/'
),
('Luxuper Firebrand Super',
'High quality ribbon microphone, following similar design design details from the Firebrand. Our magnum opus of audio capture.',
'Microphone',
499.99,
'images/'
),
('Luxuper Durandall',
'Adjustable headphones featuring active noise cancelling, ultra-fidelity, and carbon-fiber drivers.',
'Headphones',
600.00,
'images/'
),
('Luxuper Durandall W',
'Adjustable headphones featuring active noise cancelling, ultra-fidelity, and carbon-fiber drivers. Wireless model.',
'Headphones',
650.00,
'images/'
),
('Luxuper Durandall Eternal',
'Upgrade from the Durandall model, adding dual-battery mounted capability for up to 120 hours of use without charging.',
'Headphones',
689.99,
'images/'
),
('Luxuper Durandall Eternal W',
'Upgrade from the Durandall model, adding dual-battery mounted capability for up to 120 hours of use without charging. Wireless model.',
'Headphones',
739.99,
'images/'
),
('Luxuper Pugio',
'Headset microphone compatible with all Luxuper headsets. Can be mounted to either side of the headset.',
'Microphone',
79.99,
'images/'
),

-- Camera Products
('Luxuper Occhio Glimpse',
'The first of our wired cameras. 1080p, with a reliable built in microphone and pre-installed noise cancellation software.',
134.99,
'images/'
),
('Luxuper Occhio Foresight',
'4k camera with a built-in microphone, featuring modern active noise cancellation and a condenser microphone.',
179.99,
'images/'
)